#ifndef SECRETS_H
#define SECRETS_H

// WiFi credentials
#define SECRET_SSID "YOUR_SSID"
#define SECRET_PASS "YOUR_PASS"

// W3bstream configuration
#define SECRET_PROJECT_NAME "YOUR_PROJECT_NAME"
#define SECRET_EVENT_TYPE "YOUR_EVENT_TYPE"
#define SECRET_PUB_TOKEN "YOUR_PUB_TOKEN"

// Google API 
#define SECRET_GOOGLE_API "YOUR_GOOGLE_API_KEY"

#endif // SECRETS_H
